module.exports = {
    messages: {
        INVALID_DATA: "INVALID_DATA",
        BAD_REQUEST: "BAD_REQUEST",
        DATA_NOT_FOUND: "DATA_NOT_FOUND",
        INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
        INVALID_FILE_NAME: "INVALID_FILE_NAME",
        CREATE_SUCCESSFUL: "CREATE_SUCCESSFUL",
        PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
        PAYMENT_NOT_SUCCESSFUL: "PAYMENT_NOT_SUCCESSFUL",
        UPDATED_PURCHASE_FAILED: "UPDATED_PURCHASE_FAILED",
        INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
        AUTHORIZATION_REQUIRED: "AUTHORIZATION_REQUIRED",
        BAD_REQUEST_NUMBER: 401,
        INVALID_DATA_NUMBER: 403,
        DATA_NOT_FOUND_NUMBER: 404,
        SUCCESS_NUMBER: 200,
        INTERNAL_SERVER_ERROR_NUMBER: 500,
    }
};